"""tracking plans and manage keys

Revision ID: 66cdfbec3e34
Revises: 35af21c3eeb4
Create Date: 2026-09-27 00:56:35.490582

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "66cdfbec3e34"
down_revision: str | None = "35af21c3eeb4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tracking_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("plan", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_tracking_plans_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tracking_plans")),
        sa.UniqueConstraint(
            "project_id", "version", name=op.f("uq_tracking_plans_project_id_version")
        ),
    )
    op.add_column(
        "read_keys",
        sa.Column("can_manage", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("read_keys", "can_manage")
    op.drop_table("tracking_plans")
    # ### end Alembic commands ###
