"""read keys

Revision ID: 35af21c3eeb4
Revises: 779506528002
Create Date: 2026-09-27 00:35:43.451316

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "35af21c3eeb4"
down_revision: str | None = "779506528002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "read_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_read_keys_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_read_keys")),
        sa.UniqueConstraint("key_hash", name=op.f("uq_read_keys_key_hash")),
    )
    op.create_index(op.f("ix_read_keys_project_id"), "read_keys", ["project_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_read_keys_project_id"), table_name="read_keys")
    op.drop_table("read_keys")
    # ### end Alembic commands ###
