"""projects and write keys

Revision ID: 779506528002
Revises:
Create Date: 2026-09-26 23:52:51.769699

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "779506528002"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_table(
        "write_keys",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_write_keys_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_write_keys")),
        sa.UniqueConstraint("key_hash", name=op.f("uq_write_keys_key_hash")),
    )
    op.create_index(op.f("ix_write_keys_project_id"), "write_keys", ["project_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_write_keys_project_id"), table_name="write_keys")
    op.drop_table("write_keys")
    op.drop_table("projects")
    # ### end Alembic commands ###
